### ISSUE TITLE
Test Feedback: Slow Loading Time on Events API Endpoint

### ISSUE THREAD

**Issue by NigelLu** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#130]
Hello Team 3,

I've been testing your site and noticed that the GET request to API "http://cheerup-env.eba-sn3jjdga.us-east-1.elasticbeanstalk.com/events/events/" took around 7 seconds to load (I am on NYU Wi-Fi so the network speed should be okay). 

I included a screenshot below where we can see that the time spent on waiting for server response is 7.3 seconds. 

<img width="884" alt="Screenshot 2023-11-16 at 12 22 57" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/52246554/100ea945-94ae-4fa3-994d-16609c06e532">

That being said, the left half of the page (screenshot below), where you render all events directly using Django templates,  loads pretty fast. I looked into your code and it seems the only different between the index-view and the get_data view in your events app is that get_data serializes the data into JSON response. So I guess you may want to look into that and see if there is a way to improve the API endpoint get-back speed.

<img width="684" alt="Screenshot 2023-11-16 at 12 27 16" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/52246554/d8d6880a-5fb2-45a6-87c8-75d08b15f429">

**Comment by WenjunYuAnny** [comment]
Thank you very much for testing our website! Yes we're aware of the long loading time for the pins of the map. We've noted this issue in our not-to-test scenario. But still we appreciate a lot your effort and we'll work on improving it!
