### ISSUE TITLE
Editing end time while creating event

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#131]
I was unable to edit the end time while creating an event, got a invalid value error for 30 min and for 12 min
![Uploading Screenshot 2023-11-16 at 8.13.10 PM.png…]()

I was able to however set the start time and end time to be the same value, although the submit did not work, possibily can highlight that its a wrong value in that case?
<img width="1792" alt="Screenshot 2023-11-16 at 8 10 50 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/13433292/9998eb83-f4b7-4ac0-860e-a96d04f24e55">

**Comment by WenjunYuAnny** [comment]
Thanks a lot for testing on our website! We're not able to replicate the scenario you described and therefore not really able to understand the issue. We believe the validation works but it might just take time.
