### ISSUE TITLE
The same start and end time when updating

### ISSUE THREAD

**Issue by Zhiyuan-Wei** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#132]
I find I can update an event with the same start and end time. Maybe change it to end time should be later than start time?

![update](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/120235952/2aecd5cc-7b11-4003-b225-a13a271a0ba4)

**Comment by WenjunYuAnny** [comment]
Thanks a lot for testing our website! Yes we understand your point. However, we also want to keep the possibility for some very special event that may last less than 1 min. Therefore we don't really see this as a bug. But we appreciate a lot your effort!
