### ISSUE TITLE
Testing Party: No Backend Check for event deletion

### ISSUE THREAD

**Issue by Chinnu1103** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#133]
Hi, I was able to change the html using the inspect tool and was able to delete other events that I didnt even create:

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/32939338/2eeebc03-6bd6-40f9-a162-ccf0c6d75695)

For example, in the aobove image i changed the event id 27 to 19 and black friday event got deleted? (Sorry about that)

**Comment by WenjunYuAnny** [comment]
Thanks a lot for point this out! Indeed this is a bug we missed. We'll work on fixing this.
