### ISSUE TITLE
Testing Party: Deleted Events are not deleted

### ISSUE THREAD

**Issue by Chinnu1103** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#134]
I can see that the event I deleted is still visible on the new tab. For example, I deleted this event but I can still see it:

http://cheerup-env.eba-sn3jjdga.us-east-1.elasticbeanstalk.com/events/27/

**Comment by WenjunYuAnny** [comment]
Thank you very much! Yes this is another bug we missed. We'll work on the issue!
