### ISSUE TITLE
Testing Party: I was able to update event details, even though I was not the creator.

### ISSUE THREAD

**Issue by sawyer1997** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#135]
<img width="954" alt="Screenshot 2023-11-18 at 1 15 43 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-3/assets/35322947/7316a2ee-3b55-4929-8b3d-0a215fe6e7d7">

As from the image, you can see I'm not the creator, but I updated the headline of the event.

**Comment by WenjunYuAnny** [comment]
Thank you very much for pointing this out! This is indeed a bug that we missed. We'll work on fixing this!
