### ISSUE TITLE
As <a user>, I want <to be able to create a new event with an event name> so that <I can share my event>.

### ISSUE THREAD

**Issue by WenjunYuAnny** [gcivil-nyu-org/Wednesday-Fall2023-Team-3#3]
**User story**
As a user, I want to be able to create a new event with an event name so that I can share my event.

**Acceptance criteria**
By inputting an valid event name, a user can create a new entry in the event database. 
The event name should be strings.
The event name must not have malicious strings.
The event name must contain alphabet or number.
The event name can have emoji.
If the event name is not following the above requirement, the user can't create the event.

**Definition of Done**
Tests written and passing.
Acceptance criteria met.
Code peer-reviewed.
Cross-browser testing on Chrome, Safari and Firefox.

**Comment by Dhiren-NYU** [comment]
Same User will not be able to create same event twice(same event name and location and date time)
